services:
  nginx: # サービス名
    container_name: "p-nginx-docker-compose" # コンテナ名
    image: nginx:1.21.1 # 参照するimage名を指定。ここではDockerHub上のnginxイメージを指定している。
    ports:
      - "80:80" # ホストとゲストのポート番号のマッピング。
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf #ディレクトリのバインドマウント。
      - ./src:/var/www/
    depends_on:
      - php # サービス同士の依存関係
  php:
    container_name: "p-php-docker-compose"
    build: ./docker/php # ビルドする dockerfileの場所。パスを指定する。./docker/php配下のDockerfileを参照して作成
    volumes:
      - ./src:/var/www/
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: first_db #データベース名先に決めておく
      MYSQL_USER: first_user
      MYSQL_PASSWORD: first_pass
    command:
      mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
